apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: nicolaka/netshoot
        command: ["sh", "-c", "python3 -m http.server 80"]
        ports:
        - containerPort: 80
        