apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: pass123
        ports:
        - containerPort: 3306